-- mame vsetko naplnene?
select * from P_KRAJINA;
select * from P_KRAJ;
select * from P_OKRES;
select * from P_MESTO;
select * from P_ZAMESTNAVATEL;
select * from P_PLATITEL;
select * from P_OSOBA;
select * from P_ZTP;
select * from P_ZAMESTNANEC;
select * from P_POISTENIE;
select * from P_POBERATEL;
select * from P_TYP_POSTIHNUTIA;
select * from P_ODVOD_PLATBA;
select * from P_TYP_PRISPEVKU;
select * from P_HISTORIA;
select * from P_PRISPEVKY;
